import type { NextPage } from "next";
import Head from "next/head";
import Image from "../components/Image";
import styles from "../styles/Home.module.css";

const slideImages = [
  "https://vorschau.nolteundlauth.de/bewerbung/dt/01/img/img01.jpg",
  "https://vorschau.nolteundlauth.de/bewerbung/dt/01/img/img02.jpg",
  "https://vorschau.nolteundlauth.de/bewerbung/dt/01/img/img03.jpg",
  "https://vorschau.nolteundlauth.de/bewerbung/dt/01/img/img04.jpg",
  "https://vorschau.nolteundlauth.de/bewerbung/dt/01/img/img05.jpg",
];

const bgImage =
  "https://vorschau.nolteundlauth.de/mb/vo-assets/img/display_black.jpg";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div id="slidebox">
          <div id="background">
            <Image src={bgImage} alt="background" width="100%" height="100%" />
          </div>
          <Slide images={slideImages} />
        </div>
      </main>
    </div>
  );
};

export default Home;
